site_name: ComFiT documentation

theme:
  name: material
  features:
    - navigation.sections
    - toc.integrate
    - navigation.right
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

nav:
  - Home: index.md
  - Base system: ClassBaseSystem.md
  - Plotting: Plotting.md
  - Topological Defects: TopologicalDefects.md
  - "Class: Quantum Mechanics": ClassQuantumMechanics.md
  - "Class: Bose-Einstein condensate": ClassBoseEinsteinCondensate.md
  - "Class: Nematic liquid crystal": ClassNematicLiquidCrystal.md
  - "Class: Phase-field crystal": ClassPhaseFieldCrystal.md
  - "Creating your own model": CreatingYourOwnModel.md
  - Conventions: Conventions.md
  - Contributing: Contributing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: |
  &copy; 2024 <a href="https://github.com/vidarsko/ComFiT"  target="_blank" rel="noopener">Vidar Skogvoll and Jonas Rønning</a>