on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: JOSS_paper/paper.md

      - name: List files
        run: ls -lah JOSS_paper/

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: paper
          path: JOSS_paper/paper.pdf